// Game list. Edit this file to add or remove games.
// BASE is where the cartridge .js files are hosted.
var BASE = "https://cdn.jsdelivr.net/gh/KTpika/Thisisnotmine@main/";

var GAMES = [
  { name: "Abandoned",       file: "Abandoned.js"       },
  { name: "Adelie Golf",     file: "adelie_golf.js"     },
  { name: "Arielle",         file: "Arielle.js"         },
  { name: "Athos",           file: "athos.js"           },
  { name: "Auteste",         file: "auteste.js"         },
  { name: "Awake",           file: "awake.js"           },
  { name: "BlancV2",         file: "BlancV2.js"         },
  { name: "Break the Targets", file: "breakthetargets.js" },
  { name: "Cafe",            file: "Cafe.js"            },
  { name: "Caligo",          file: "caligo.js"          },
  { name: "Caroline",        file: "caroline.js"        },
  { name: "Celeste",         file: "celeste.js"         },
  { name: "Collab",          file: "Collab.js"          },
  { name: "Dark Celeste",    file: "DarkCeleste.js"     },
  { name: "Darkworld",       file: "darkworld.js"       },
  { name: "Denali",          file: "denali.js"          },
  { name: "Duality",         file: "Duality.js"         },
  { name: "Everred",         file: "everred.js"         },
  { name: "Factory",         file: "Factory.js"         },
  { name: "Falleste",        file: "falleste.js"        },
  { name: "Farland",         file: "farland.js"         },
  { name: "Farland V2",      file: "farlandv2.js"       },
  { name: "Flare",           file: "flare.js"           },
  { name: "Flip",            file: "Flip.js"            },
  { name: "Foraker",         file: "foraker.js"         },
  { name: "Foreverred",      file: "foreverred.js"      },
  { name: "Fuji",            file: "fuji.js"            },
  { name: "Funklost",        file: "Funklost.js"        },
  { name: "Games",           file: "games.js"           },
  { name: "Getting Over It", file: "GettingOverIt.js"   },
  { name: "Hallowneste",     file: "hallowneste.js"     },
  { name: "Helleste",        file: "helleste.js"        },
  { name: "Helpdelie",       file: "helpdelie.js"       },
  { name: "Ingeste",         file: "Ingeste.js"         },
  { name: "Jank",            file: "Jank.js"            },
  { name: "Kaizoleste",      file: "kaizoleste.js"      },
  { name: "Labeste",         file: "labeste.js"         },
  { name: "Lasal",           file: "lasal.js"           },
  { name: "Maddyx",          file: "Maddyx.js"          },
  { name: "Mademaker",       file: "mademaker.js"       },
  { name: "Muteste",         file: "Muteste.js"         },
  { name: "Noeleste",        file: "Noeleste.js"        },
  { name: "Nostalgia",       file: "nostalgia.js"       },
  { name: "Nowhere",         file: "nowhere.js"         },
  { name: "Oldeste",         file: "oldeste.js"         },
  { name: "Oldsite",         file: "Oldsite.js"         },
  { name: "Peril",           file: "peril.js"           },
  { name: "Perisher",        file: "perisher.js"        },
  { name: "Practice",        file: "Practice.js"        },
  { name: "Procgen",         file: "Procgen.js"         },
  { name: "Puzzle",          file: "Puzzle.js"          },
  { name: "Rainier",         file: "rainier.js"         },
  { name: "Rainier 2",       file: "rainier2.js"        },
  { name: "Rift",            file: "rift.js"            },
  { name: "Rosetta",         file: "rosetta.js"         },
  { name: "Ruins",           file: "Ruins.js"           },
  { name: "Scrolleste",      file: "scrolleste.js"      },
  { name: "Snek",            file: "Snek.js"            },
  { name: "Sparkleste",      file: "Sparkleste.js"      },
  { name: "Switch",          file: "switch.js"          },
  { name: "Techtrain3",      file: "techtrain3.js"      },
  { name: "Terra Australis", file: "Terra_Australis.js" },
  { name: "Vector",          file: "Vector.js"          },
  { name: "Volcana",         file: "volcana.js"         },
];
