// Game list. Edit this file to add or remove games.
// BASE is where the cartridge .js files are hosted.
var BASE = "https://cdn.jsdelivr.net/gh/KTpika/Thisisnotmine@main/";

var GAMES = [
  { name: "Abandoned",         file: "Abandoned.js"        },
  { name: "Adelie Golf",       file: "adelie_golf.js"      },
  { name: "Amazon",            file: "amazon.js"           },
  { name: "Arielle",           file: "Arielle.js"          },
  { name: "Athos",             file: "athos.js"            },
  { name: "Auteste",           file: "auteste.js"          },
  { name: "Awake",             file: "awake.js"            },
  { name: "BlancV2",           file: "BlancV2.js"          },
  { name: "Break the Targets", file: "breakthetargets.js" },
  { name: "Bump Jump Mania",   file: "bumpjumpmania.js"    },
  { name: "Bunny Lester",      file: "bunnylestereupload.js" },
  { name: "Burning Trail",     file: "burningtrail.js"     },
  { name: "Cafe",              file: "Cafe.js"             },
  { name: "Caldera",           file: "caldera.js"          },
  { name: "Caligo",            file: "caligo.js"           },
  { name: "Caroline",          file: "caroline.js"         },
  { name: "Cc Downside",       file: "ccdownside.js"       },
  { name: "Celeste",           file: "celeste.js"          },
  { name: "Celestial Valley",  file: "celestial_valley.js" },
  { name: "Collab",            file: "Collab.js"           },
  { name: "Dark Celeste",      file: "DarkCeleste.js"      },
  { name: "Darkesthour",       file: "Darkesthour.js"      },
  { name: "Darkworld",         file: "darkworld.js"        },
  { name: "Denali",            file: "denali.js"           },
  { name: "Duality",           file: "Duality.js"          },
  { name: "Eiger",             file: "eiger.js"            },
  { name: "Everred",           file: "everred.js"          },
  { name: "Factory",           file: "Factory.js"          },
  { name: "Fairway",           file: "fairway.js"          },
  { name: "Falleste",          file: "falleste.js"         },
  { name: "Farland",           file: "farland.js"          },
  { name: "Farland V2",       file: "farlandv2.js"        },
  { name: "Filament",          file: "filament.js"         },
  { name: "Flare",             file: "flare.js"            },
  { name: "Flip",              file: "Flip.js"             },
  { name: "Foraker",           file: "foraker.js"          },
  { name: "Foreverred",        file: "foreverred.js"       },
  { name: "Frozen Caves",      file: "frozencaves.js"      },
  { name: "Fuji",              file: "fuji.js"             },
  { name: "Funklost",          file: "Funklost.js"         },
  { name: "Games",             file: "games.js"            },
  { name: "Getting Over It",   file: "GettingOverIt.js"    },
  { name: "Gock V1",           file: "gockV1.js"           },
  { name: "Gym",               file: "gym.js"              },
  { name: "Hallowneste",       file: "hallowneste.js"      },
  { name: "Helleste",          file: "helleste.js"         },
  { name: "Helpdelie",         file: "helpdelie.js"        },
  { name: "Hollow Knight",     file: "HollowKnight.js"     },
  { name: "Ingeste",           file: "Ingeste.js"          },
  { name: "Jank",              file: "Jank.js"             },
  { name: "Kaizoleste",        file: "kaizoleste.js"       },
  { name: "Labeste",           file: "labeste.js"          },
  { name: "Labyrinth",         file: "labyrinth.js"        },
  { name: "Lasal",             file: "lasal.js"            },
  { name: "Maddy on Moon",     file: "maddy_on_moon.js"    },
  { name: "Maddyx",            file: "Maddyx.js"           },
  { name: "Mademaker",         file: "mademaker.js"        },
  { name: "Mt Fua",            file: "mt_fua.js"           },
  { name: "Muteste",           file: "Muteste.js"          },
  { name: "Noeleste",          file: "Noeleste.js"         },
  { name: "Nostalgia",         file: "nostalgia.js"        },
  { name: "Nowhere",           file: "nowhere.js"          },
  { name: "Oldeste",           file: "oldeste.js"          },
  { name: "Oldsite",           file: "Oldsite.js"          },
  { name: "Peril",             file: "peril.js"            },
  { name: "Perisher",          file: "perisher.js"         },
  { name: "Picochu",          file: "picochu.js"          },
  { name: "Practice",          file: "Practice.js"         },
  { name: "Procgen",           file: "Procgen.js"          },
  { name: "Puzzle",            file: "Puzzle.js"           },
  { name: "Puzzle Mod",        file: "puzzlemod.js"        },
  { name: "Rainier",           file: "rainier.js"          },
  { name: "Rainier 2",         file: "rainier2.js"         },
  { name: "Real Kaileste",     file: "realkaileste.js"     },
  { name: "Rift",              file: "rift.js"             },
  { name: "Rosetta",           file: "rosetta.js"          },
  { name: "Roundelie Rescue",  file: "roundelierescue.js"  },
  { name: "Ruins",             file: "Ruins.js"            },
  { name: "Salt",              file: "salt.js"             },
  { name: "Scoliosis",         file: "scoliosis.js"        },
  { name: "Scrolleste",        file: "scrolleste.js"       },
  { name: "Snek",              file: "Snek.js"             },
  { name: "Solanum",           file: "solanum.js"          },
  { name: "Sparkleste",        file: "Sparkleste.js"       },
  { name: "Sterrenmeid",       file: "sterrenmeid.js"      },
  { name: "Sugarrush",         file: "sugarrush.js"        },
  { name: "Summer",            file: "summer.js"           },
  { name: "Switch",            file: "switch.js"           },
  { name: "Switch 60FPS",      file: "switch60fps.js"      },
  { name: "Techtrain 3",       file: "techtrain3.js"       },
  { name: "Terra Australis",   file: "Terra_Australis.js"  },
  { name: "Theos Return",      file: "theos_return.js"     },
  { name: "True North",        file: "truenorth.js"        },
  { name: "Ultimate Selfie",   file: "ultimate_selfie.js"  },
  { name: "Vector",            file: "Vector.js"           },
  { name: "Volcana",           file: "volcana.js"          },
  { name: "Wreck",             file: "Wreck.js"            },
  { name: "Winterglass",       file: "winterglass.js"      }
];
